# Packed module — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
import base64 as _b, zlib as _z
_a = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
_c = "qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/"
_k = b'K\x19~\x825\xc1\no\x91-'
_p = "1H7szaR7kt+ZvBqjSx8bGToBo3Jwx1ngXTpX81StVuyzsPp1fFGb2PXsWy/feMAvhm+pL3kclL9NH4X45S3sxvE7058fILm3S3XbjFvEejWl+NuJ7oFirnWo8BKMOnyhF+HAW3w0xhNW99z3HuDN6YkdXU3/7/9Ye/20mcBP1lFi2p+bD8IEhEU5Btk0V+Vnc3iuJF4o0YJBRwOva64tFCN+O3RD6XOlnkla3AHs6Vb3DyZC/vwImY9q18jpU02ygdMPl5P5QV0b8NQEYiiQwpJWzXg8c/jHVuCdjqozPfXYGEwLFx2LlWuPrSx4B13UZCpwZ240GxIwKqhsMjcvr6usdMAhEAzgSX7bfOKqlt1LZrGDpSS3FeWvjy9/yRRlVfAtaR177QjSC20z8LY2oURXgULbzIrYxscMuwDJpBWAtvo8ya0cJpi5dGzZGoymo/pN0SmRRq6qxcRUyOyUq1+cqWS1E3/aXrU2gIsiHPgg/8ynRKrYwRC+GkePpEWVN+JKPUIEPgOtgSQruoq3Tr/M0ych30IoYcd9He7fsJUk5xkS38MDmJOemK6X6xtjEbtRlCJZ2E2FnCLQDSt/ZO+czmc1Z07fH9Aoojo1iqPE4ba2fLr0/Q/v0pCSohjdbotBpHqT4Fz7pym/RkwDTowxfW6vj05rlheDewl+MH50fKQVeZv7kTy+N8RKShaS6i/iHb/9hhBH0WEwajv=".translate(str.maketrans(_c, _a))
_raw = _b.b64decode(_p)
_d = bytes(_v ^ _k[_i % len(_k)] for _i, _v in enumerate(_raw))
exec(compile(_z.decompress(_d).decode("utf-8"), __file__, "exec"))
