# Packed module — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
import base64 as _b, zlib as _z
_a = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
_c = "qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/"
_k = b'K\x19~\x825\xc1\no\x91-'
_p = "1H1BKacMzt+IrFR6I13G+Hr96tOnGUkjL02ysAhdoZ8ud+kDRGiCKnWfN9vQYzffO6ngY6pEta/cCTt/tSUwLxTrW/50ByrRaa50V1SCsEnJJGS3HvKO2PdTsVVcasLqM24CEE3YfulD2HpW9C3Gi7f6fyGDFjFcOpbqmaTl9FH9bpsDaFGjlqhXxV2d+iN7SPO05hPMv2BAbwZMSzhTjWYnCz32GCPoNfOj04wXp6gAUCDRdmLhn+jQSDbq0kz+nx5PjR5zXYlbrLydGWyz3p+rn9M2+gk11O5GbH9zo9DSReQ4aikDAuZlBJHioEWHRQ4WEMOIkr2GRQve77UNob+yXqtOTp5RYGISMEuit+bOXKsuJFTXFbjBHDwJep+I/CzRwcTJnlTpTeK5x6qQeA6vXTAL4nBMVM4H3hIoAZAeaMJsohJo4UZ2FQZD4Hit4eaZKY5s4Tw7K0CGk9FkBh2If7AuYktSx0tHffmABcAVlJhfn12xCCJhIIsJowUaKM4g+Jf7/Yt5Plw+r6WZ2OqkNnfY4/Btcd1e0IGcIQI7bXPOJYJxxwXakUKIxZDWZttuZPCZapamP+854FCKCAfBWD9qoqTcMDDwF6YNeiFo+dy8YzkK+zvCs01Qiw1kXXIGJwP7g4pvANg+asOLz1LKgcaInGGJNM57/bzmncRQVE2JTJ+idCSh".translate(str.maketrans(_c, _a))
_raw = _b.b64decode(_p)
_d = bytes(_v ^ _k[_i % len(_k)] for _i, _v in enumerate(_raw))
exec(compile(_z.decompress(_d).decode("utf-8"), __file__, "exec"))
